### ISSUE TITLE
build_run do not work.

### ISSUE THREAD

**Issue by ivanlunardi** [gi097/flutter_clickable_regions#1]
I trie your example but do not work 

`
NoSuchMethodError: The getter 'futureDynamicType' was called on null.
Receiver: null
Tried calling: futureDynamicType
dart:core                                                       Object.noSuchMethod
package:analyzer/src/dart/element/element.dart 7120:40          LibraryElementImpl.createLoadLibraryFunctionForLibrary
package:analyzer/src/dart/element/element.dart 6968:9           LibraryElementImpl.createLoadLibraryFunction
package:analyzer/src/summary/resynthesize.dart 332:24           SummaryResynthesizer.getLibraryElement.<fn>
dart:collection                                                 _LinkedHashMapMixin.putIfAbsent
package:analyzer/src/summary/resynthesize.dart 320:36           SummaryResynthesizer.getLibraryElement
package:analyzer/src/summary/resynthesize.dart 382:20           SummaryResynthesizer._buildTypeProvider
package:analyzer/src/summary/resynthesize.dart 180:5            new SummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 340:9   new StoreBasedSummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 320:26  ResynthesizerResultProvider.createResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 79:5    new InputPackagesResultProvider
package:analyzer/src/dart/sdk/sdk.dart 98:19                    AbstractDartSdk.context
package:analyzer/src/context/context.dart 1975:46               PartitionManager.forSdk
package:analyzer/src/context/context.dart 744:50                AnalysisContextImpl.createCacheFromSourceFactory.createCache
package:analyzer/src/context/context.dart 749:38                AnalysisContextImpl.createCacheFromSourceFactory
package:analyzer/src/context/context.dart 476:14                AnalysisContextImpl.sourceFactory=
package:build_resolvers/src/resolver.dart 91:14                 new AnalyzerResolver
package:build_resolvers/src/resolver.dart 435:32                new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 130:23      BuildOptions.create
package:build_runner/src/generate/build.dart 78:36              build
package:build_runner/src/entrypoint/build.dart 28:24            BuildCommand.run
package:args/command_runner.dart 197:27                         CommandRunner.runCommand
package:args/command_runner.dart 112:25                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 112:14                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31              run
.dart_tool/build/entrypoint/build.dart 18:22                    main

pub finished with exit code 1
`

**Comment by gi097** [comment]
Thanks for the issue. I will take a look in this later today and I will get back to you soon.

**Comment by gi097** [comment]
I think you are using a too recent `build_runner`. Can you try it with the older version `0.9.2` first?

**Comment by pamarcan** [comment]
hi, after fixing the dependencies I ran the command

flutter packages pub run build_runner build

The script works but no output file is created

This is the output of the command

[INFO] Generating build script ...
[INFO] Generating build script completed, took 238ms

[INFO] Creating build script snapshot ......
[INFO] Creating build script snapshot ... completed, took 9.9s

[SEVERE] Nothing can be built, yet a build was requested.
[INFO] Initializing inputs
[INFO] Building new asset graph ...
[INFO] Building new asset graph completed, took 663ms

[INFO] Checking for unexpected pre-existing outputs ....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build ...
[INFO] Running build completed, took 4ms

[INFO] Caching finalized dependency graph ...
[INFO] Caching finalized dependency graph completed, took 53ms

[INFO] Succeeded after 69ms with 0 outputs (0 actions)

I haven't changed anything in the map_svg_data.dart file, but I don't know how the 'part' directive works, can you tell me where I can get information?

thanks

**Comment by gi097** [comment]
You can now use the latest `build_runner` in the example since commit 48dcf00. 

Output:
```
flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 447ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 14.1s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.1s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 4.5s elapsed, 0/2 actions completed.
[INFO] Generating SDK summary completed, took 4.5s

[INFO] 5.6s elapsed, 1/2 actions completed.
[INFO] 7.8s elapsed, 1/2 actions completed.
[INFO] 14.6s elapsed, 2/2 actions completed.
[INFO] Running build completed, took 14.6s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 46ms

[INFO] Succeeded after 14.7s with 1 outputs (5 actions)
```

**Comment by ivanlunardi** [comment]
Hi have tried copy your package inside my project with this dependency and it works

`dependencies:`
`  analyzer: ^0.39.4`
 ` build: ^1.2.2`
 ` built_path_annotations: `
`    path: '../built_path_annotations'`
`  # built_path_annotations:`
 ` #   path: ../built_path_annotations`
 ` path_parsing: ^0.1.2`
 ` source_gen: ^0.9.0`
 ` # flutter:`
`  #   sdk: flutter`

`dev_dependencies:`
  build_config: ^0.3.1`
`  build_runner: ^1.7.3`
