### ISSUE TITLE
undefined name issue

### ISSUE THREAD

**Issue by show111-zz** [gi097/flutter_clickable_regions#2]
I wanna run the example after I ran the command 'flutter packages pub run build_runner build' in the terminal.
there are several errors show in the line of 'static Path get noordBrabant => _$MapSvgData_noordBrabant;'
and the error tips said that"undefined name '_$MapSvgData_noordBrabant', 
do you know what else I can do? Thanks

**Comment by gi097** [comment]
Can you provide me the error log?

**Comment by show111-zz** [comment]
Because build_runner >=1.7.1 depends on build >=1.0.0 <1.3.0 and built_path 0.1.0 depends on build ^0.12.7, build_runner >=1.7.1 is incompatible with built_path 0.1.0.

And because no versions of built_path match >0.1.0 <0.2.0, build_runner >=1.7.1 is incompatible with built_path ^0.1.0.

So, because flutter_app depends on both built_path ^0.1.0 and build_runner ^1.7.4, version solving failed.
pub get failed (1; So, because flutter_app depends on both built_path ^0.1.0 and build_runner ^1.7.4, version solving failed.)

**Comment by show111-zz** [comment]
and my pubspec.yaml file looks like this:

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_map: 0.8.2
  flutter_svg: ^0.17.3+1
  drawing_animation: ^0.1.3
  built_path: ^0.1.0

dev_dependencies:
  build_runner: ^1.7.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

**Comment by gi097** [comment]
Make sure you have the following in your `pubspec.yaml`, which is included in this repo:

```yaml
dependency_overrides:
  analyzer: ^0.39.4
  build: ^1.2.2
```

**Comment by show111-zz** [comment]
yeah. thanks a lot.
