### ISSUE TITLE
Building the @SvgPath and invoke the SvgPathGenerator dynamically

### ISSUE THREAD

**Issue by zenkog** [gi097/flutter_clickable_regions#4]
Hi,

First of all I wanna praise this brilliant work! Amazing!

I have a project where the app will get different SVG files and the app needs to make the areas clickable in the app. Thus it needs to be able to parse the SVG file and make it into that @SvgPath then automatically invoke the SvgPathGenerator to make that 'map_svg_data.svg_path.g.dart' file.

Any pointers will be very much appreciated.. Thank you so much!!

**Comment by gi097** [comment]
You can take a look at the library `flutter_built_path` which this example is using: https://github.com/dnfield/flutter_built_path

That repository contains logic of parsing SVG's and generating a file, instead you could use this logic to generate actual `Path` objects.

**Comment by zenkog** [comment]
Thanks for the pointer. I saw this before. But it is parsing the SVG string that is already looks like this: 'M10 10 L20 20 Z' 

But most SVG String when derived from a file it look like this:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path d="M30,1h40l29,29v40l-29,29h-40l-29-29v-40z" stroke="#000" fill="none"/> 
  <path d="M31,3h38l28,28v38l-28,28h-38l-28-28v-38z" fill="#a23"/> 
  <text x="50" y="68" font-size="48" fill="#FFF" text-anchor="middle"><![CDATA[410]]></text>
</svg>`

So I aim to remove all the other tags and just get all the strings after '<path d=' and also the fill color.
