### ISSUE TITLE
All path are like drawn on same position

### ISSUE THREAD

**Issue by newbieflutter** [gi097/flutter_clickable_regions#6]
Hi I have tried to modified and insert my own paths. All works fine except that the path like all drawn on one position and some are over lapping. They supose to be like from top to bottom. How to overcome that?

**Comment by gi097** [comment]
It depends on the SVG image being used. If you are using seperate SVG images you need to position them yourself. In this example I used a single SVG image and picked the paths manually. Since those paths are in the same image, I didn't need to position them.
